config/routes.rb
Remont::Application.routes.draw do
  resources :users

  match 'signup', :to => 'users#new', :as => 'signup'
  match 'contact', :to => 'pages#contact', :as => 'contact'
  match 'about', :to => 'pages#about', :as => 'about'
  match 'help', :to => 'pages#help', :as => 'help'
  
  root :to => 'pages#home'

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	validates :name, :presence => true,
					 :length => { :maximum => 50 }
	validates :email, :presence => true,
					  :format => { :with => email_regex },
					  :uniqueness => { :case_sensitive => false }
	validates :password, :presence => true, 
						 :confirmation => true,
						 :length => { :within => 6..40}
						 
	before_save :encrypt_password
	
	def has_password?(submitted_password)
	encrypted_password == encrypt(submitted_password)
	end
	
	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end
	
	# szyfrowanie hasel
		
	private
	
		def encrypt_password
			self.salt = make_salt unless has_password?(password)
			self.encrypted_password = encrypt(password)
		end
		
		def encrypt(string)
			secure_hash("#{salt}--#{string}")
		end
		
		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end
		
		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
					 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  @title = "Główna"
  end

  def contact
  @title = "Kontakt"
  end
  
  def about
  @title = "O nas"
  end
  
  def help
  @title = "Pomoc"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  @title = "Rejestracja"
  end
  
  def show
  @user = User.find(params[:id])
  @title = @user.name
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def logo
		logo = image_tag("images/logo.png", :alt => "Remont", :class => "round") 
	end
	
	def title
		base_title = "Remont"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
	def gravatar_for(user, options = { :size => 50 })
	gravatar_image_tag(user.email.downcase, :alt => user.name,
											:class => 'gravatar',
											:gravatar => options)
	end
		
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "O nas", about_path %></li>
      <li><%= link_to "Kontakt", contact_path %></li>    
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
   <header>
        <%= link_to logo, root_path %>
        <nav class="round">
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Pomoc", help_path %></li>
            <li><%= link_to "Zaloguj się", '#' %></li>
          </ul>
        </nav>
      </header>

app/views/layouts/_stylesheets.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <%= stylesheet_link_tag 'screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
		<%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
    <h1>O nas</h1>
    <p>
      Strona o autorach projektu remont
    </p>

app/views/pages/contact.html.erb
    <h1>Kontakt</h1>
    <p>
      Strona kontaktowa projektu remont
    </p>

app/views/pages/help.html.erb
    <h1>Pomoc</h1>
    <p>
      W sprawach problemów z funkcjonowaniem serwisu proszę o kontakt z administratorem <br />
	  flaqmastahgf@gmail.com
    </p>

app/views/pages/home.html.erb
 <h1>Główna</h1>
	<p>
	Strona główna projektu remont
 </p>
	<%= link_to "Zarejestruj się!", signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Nazwa</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>